ci/cu2d-trigger /usr/bin
ci/cu2d-update-ci /usr/bin
ci/config/* /usr/share/cupstream2distro-config/ci/config
ci/jenkins-templates/* /usr/share/cupstream2distro-config/ci/jenkins-templates
daily-release/cu2d-update-stack /usr/bin
daily-release/config/* /usr/share/cupstream2distro-config/daily-release/config
daily-release/jenkins-templates/* /usr/share/cupstream2distro-config/daily-release/jenkins-templates
stacks/* /etc/cupstream2distro-config/stacks
