#!/usr/bin/env python
""" Check stalled merge proposals -- i.e. merge proposals that are approved
but not merged for a longer period of time
"""
# Copyright (C) 2013, Canonical Ltd (http://www.canonical.com/)
#
# Author: Martin Mrazik <martin.mrazik@canonical.com>
#
# This software is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
sys.path.append('..')  # add local cupstream2distro

from c2dconfigutils.cu2dWatchDog import CheckStalledMPs

BASEDIR = os.path.dirname(__file__)

if __name__ == "__main__":
    command = CheckStalledMPs()
    sys.exit(command(BASEDIR))
